### ISSUE TITLE
이 책에서 사용한 매크로를 리눅스에서도 활용할 수 있나요?

### ISSUE THREAD

**Issue by leeyunhome** [needleworm/bhban_RPA#1]
안녕하세요?

이 책에서 사용한 매크로를 리눅스에서도 활용할 수 있나요?

**Comment by needleworm** [comment]
안녕하세요.

본 책의 매크로는 윈도우의 핵심 모듈 중 하나인 win32api를 활용합니다. 따라서 윈도우에서만 작동 가능함을 안내드립니다.
조만간 맥과 리눅스용도 추가해 보도록 하겠습니다.

**Comment by needleworm** [comment]
업데이트가 추가되었습니다. 이제 맥과 리눅스에서도 정상적으로 작동합니다.

**Comment by leeyunhome** [comment]
> 업데이트가 추가되었습니다. 이제 맥과 리눅스에서도 정상적으로 작동합니다.

감사합니다~

**Comment by leeyunhome** [comment]
> 업데이트가 추가되었습니다. 이제 맥과 리눅스에서도 정상적으로 작동합니다.

안녕하세요?
새로 클론했는데 리눅스에서는 여전히 동작을 안해서요.
혹시 업데이트가 제대로 되었는지 확인 부탁드려도 될까요?

감사합니다.

**Comment by leeyunhome** [comment]
> 업데이트가 추가되었습니다. 이제 맥과 리눅스에서도 정상적으로 작동합니다.

리드미를 읽어보니 새로운 매크로가 추가되었네요

감사합니다.

**Comment by needleworm** [comment]
안녕하세요. 제가 설명이 불충분했습니다.

https://github.com/needleworm/pymacro

수정된 것은 본문 코드가 아니라 매크로입니다. 기존 pywinmacro.py 파일을 위 레포지토리의 코드로 교체하시면 정상적으로 작동할 것입니다.

조만간 조금 더 상세한 공지를 준비하겠습니다. 감사합니다!
