### ISSUE TITLE
저자님의 책 45페이지에서 git clone도 Download ZIP도 진행이 안됩니다. 제가 뭘 잘못하고 있는지 모르겠습니다.

### ISSUE THREAD

**Issue by uglydoll76** [needleworm/bhban_RPA#3]
저자님의 bhban_rpa 방문하여 fork 했더니 저의 github에 생겼습니다. 
그 후  Code버튼 눌러 Download ZIP해도, 해당 ZIP파일이 잘못되었다는 창이 뜨고 압축이 해제되지 않습니다.
또한 Git Bash에서 git clone으로 하려고 해도 에러가 나고 진행이 되지 않습니다. 

제가 뭘 잘못하고 있는 걸까요? 아무것도 모르는 문과생이 저자님의 책을 보고 생에 최초 시도를 하고 있는 중입니다.
도움 부탁 드립니다. 감사합니다.

**Comment by needleworm** [comment]
안녕하세요. 아마 인터넷의 보안 설정 때문인 것 같습니다. 예전에 모 금융사에서 인터넷 접속에 시도할 때에도 다운로드가 막혀 있더라고요.

빠른 시일 내에 코드를 다운받을 수 있는 다른 루트를 마련해 드리도록 하겠습니다.

**Comment by needleworm** [comment]
혹은 우선 책 홈페이지에서 다운로드를 시도해 보시기 바랍니다. 될 수도 있으니까요.

https://needleworm.github.io/bhban_rpa

**Comment by uglydoll76** [comment]
신속한 답변 감사합니다. 
안타깝게도 지금 필요한 압축파일 폴더는 위에 적어주신 책 홈페이지에도 깃허브 링크만 있는 것 같습니다.
책에 저술하신 대로 따라할 수 있도록 도움 부탁 드립니다. 감사합니다.

**Comment by uglydoll76** [comment]
그런데, 제가 지금 회사에서 하는 것이 아니라 집에서 하는 것이라서 보안 설정때문일지 잘 모르겠습니다.
zip 폴더가 다운은 되는데 압축해제가 안되는 상황이라서... 좀 난감해하고 있습니다. ^^

**Comment by needleworm** [comment]
다운로드된 압축파일의 용량을 확인해보시고, 0으로 기재된다면 브라우저를 바꿔서 재시도해 보시기 바랍니다. 용량이 정상적이라면 압축해제에 사용하는 소프트웨어를 반디집, 알집, 7zip 등 여러 종류로 시도해 보시기 바랍니다.

**Comment by uglydoll76** [comment]
작가님, 책 홈페이지에서 파일 찾아서 다운 받았습니다.
이걸로 해 보겠습니다. 감사합니다.

**Comment by uglydoll76** [comment]
책 홈페이지의 해당 목차에는 github 링크가 되어있어서 몰랐는데, PART2의 첫 "회원 개인정보 파일 1천 개, 1초 만에 만들기"가 47페이지에서 언급된 파일 폴더인 것 같네요. 될 것 같습니다 감사합니다.

**Comment by needleworm** [comment]
네 다행입니다 해결되셨으니 이슈를 닫겠습니다
