### ISSUE TITLE
2_5_5_명함 1천개 만들기 에서 ImportError("The _imagingft C module is not installed" 문제

### ISSUE THREAD

**Issue by s375301** [needleworm/bhban_RPA#4]
안녕하세요!

덕분에 RPA에 대해서 재밌게 배우고 있는 대학생입니다.
2_5_5에서 ImportError가 제목과 같이 뜨는데 혹시 해결방법이 있을까요??
Ubunto에서 아래와 같이 libfreetype6를 다운해보라는 것은 찾았는데 윈도우에서는 cmd에서
해당 명령어가 실행이 안돼서 헤매고 있습니다.
```
sudo apt-get install libfreetype6-dev
sudo pip uninstall pillow
sudo pip install --no-cache-dir pillow
```
[참고1](https://mickael-k.tistory.com/200)
[참고2](https://doprogramming.tistory.com/23)

미리 감사드립니다!

**Comment by needleworm** [comment]
안녕하세요. 드문 경우네요.

터미널에서 아래 명령어를 입력하여 Pillow를 삭제합니다

pip uninstall pillow

그리고 아래 링크로 접속하시어 Pil을 재설치해주시기 바랍니다.

https://python-pillow.org

위 방법으로도 해결되지 않으시면 다시 한 번 질문을 남겨주시기 바랍니다. 감사합니다.

**Comment by s375301** [comment]
감사합니다! 답변이 엄청 빠르셔서 깜짝 놀랐습니다 ㅎㅎ

혹시나 같은 문제를 겪는 사람들을 위해 코드 아래에 남겨놓도록 하겠습니다.

1. 터미널(cmd) 실행
2. 아래의 코드를 순서대로 실행
```
pip uninstall pillow
python -m pip install --upgrade pip
python -m pip install --upgrade Pillow
```
