### ISSUE TITLE
ipython 설치가 되지 않습니다

### ISSUE THREAD

**Issue by eklee980** [needleworm/bhban_RPA#7]
안녕하세요 책을 보며 따라하고 있는 중인데요

46페이지 pip install ipython을 쳐도 ipython 설치가 되지 않고

WARNING: There was an error checking the latest version of pip.라는 메세지가 뜨네요.

python은 3.11을 설치했습니다.

답변 부탁드려요^^

**Comment by needleworm** [comment]
안녕하세요. 파이썬 설치과정에서 PIP이 환경번수에 등록되지 않은 상황입니다.
https://puleugo.tistory.com/18
위 링크를 참고해 보시기 바랍니다.
감사합니다.
