### ISSUE TITLE
전 직원 비상연락망 엑셀 합치기가 안됩니다.

### ISSUE THREAD

**Issue by ektkdlaekd** [needleworm/bhban_RPA#8]
U.process(file_list) 를 입력하면 오류가 나오네요.
이유를 알고 싶습니다.

**Comment by needleworm** [comment]
안녕하세요. PyExcel 라이브러리 문제인 것으로 보입니다.
제작자에게 재차 문의를 드렸사오니 우선은 엑셀 파트는 건너뛰고 진행해 보시고,
추후 PyExcel을 재설치하고 실행해 보시기 바랍니다.
